import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/app_theme.dart';
import '../../../core/friendly_error.dart';
import '../../../providers/business/merchant_business_provider.dart';
import '../../../services/business/merchant_business_service.dart';
import '../../../routes/app_router.dart';
import '../../widgets/kp_widgets.dart';

class BusinessVerificationPage extends ConsumerStatefulWidget { const BusinessVerificationPage({super.key}); @override ConsumerState<BusinessVerificationPage> createState() => _State(); }
class _State extends ConsumerState<BusinessVerificationPage> {
  final gst = TextEditingController(), holder = TextEditingController(), account = TextEditingController(), ifsc = TextEditingController(), bank = TextEditingController();
  String type = 'Proprietorship'; bool busy = false; String? notice, error;
  Future<void> kyc() async { setState(() { busy = true; error = null; }); try { await MerchantBusinessService().submitKyc({'gstNumber': gst.text.trim().toUpperCase(), 'businessType': type, 'businessProofUrl': ''}); setState(() => notice = 'Business KYC submitted for review.'); ref.invalidate(merchantDashboardProvider); } catch (e) { setState(() => error = friendlyErrorMessage(e, fallback: 'KYC could not be submitted.')); } finally { setState(() => busy = false); } }
  Future<void> saveBank() async { if ([holder, account, ifsc].any((c) => c.text.trim().isEmpty)) { setState(() => error = 'Enter account holder, account number and IFSC.'); return; } setState(() { busy = true; error = null; }); try { await MerchantBusinessService().submitBank({'accountHolderName': holder.text.trim(), 'accountNumber': account.text.trim(), 'ifscCode': ifsc.text.trim().toUpperCase(), 'bankName': bank.text.trim()}); setState(() => notice = 'Settlement bank account submitted for verification.'); ref.invalidate(merchantDashboardProvider); } catch (e) { setState(() => error = friendlyErrorMessage(e, fallback: 'Bank account could not be submitted.')); } finally { setState(() => busy = false); } }
  @override Widget build(BuildContext context) => KpAppShell(title: 'Business verification', onRefresh: () async => ref.invalidate(merchantDashboardProvider), children: [
    if (notice != null) KpNoticeBanner(icon: Icons.check_circle_outline, color: KhatuColors.success, message: notice!), if (error != null) KpErrorBanner(message: error!),
    ref.watch(merchantDashboardProvider).when(loading: () => const LinearProgressIndicator(), error: (e, _) => KpErrorState.fromError(e), data: (d) => KpCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(d.business?.businessName ?? 'Business profile', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900)), const SizedBox(height: 10), _status('Personal KYC', d.kyc?['status'] ?? 'Required'), _status('Settlement bank', d.bank?['status'] ?? 'Required'), _status('Business approval', d.business?.status ?? 'Draft')]))),
    const KpSectionHeader(title: 'Business KYC'), KpCard(child: Column(children: [DropdownButtonFormField<String>(initialValue: type, decoration: const InputDecoration(labelText: 'Business type'), items: ['Proprietorship','Partnership','Private Limited','LLP','Other'].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(), onChanged: (v) => type = v ?? type), const SizedBox(height: 12), TextField(controller: gst, textCapitalization: TextCapitalization.characters, decoration: const InputDecoration(labelText: 'GSTIN (optional)', prefixIcon: Icon(Icons.receipt_long_outlined))), const SizedBox(height: 12), SizedBox(width: double.infinity, child: ElevatedButton.icon(onPressed: busy ? null : kyc, icon: const Icon(Icons.verified_user_outlined), label: const Text('Submit verified PAN & Aadhaar KYC'))), TextButton(onPressed: () => router.push('/kyc'), child: const Text('Complete personal KYC'))])),
    const KpSectionHeader(title: 'Settlement bank account'), KpCard(child: Column(children: [for (final entry in [(holder,'Account holder name'),(account,'Account number'),(ifsc,'IFSC code'),(bank,'Bank name (optional)')]) ...[TextField(controller: entry.$1, textCapitalization: entry.$1 == ifsc ? TextCapitalization.characters : TextCapitalization.none, decoration: InputDecoration(labelText: entry.$2)), const SizedBox(height: 12)], SizedBox(width: double.infinity, child: ElevatedButton.icon(onPressed: busy ? null : saveBank, icon: const Icon(Icons.account_balance_outlined), label: const Text('Submit bank account')))])),
  ]);
  Widget _status(String label, dynamic status) => ListTile(contentPadding: EdgeInsets.zero, leading: const Icon(Icons.check_circle_outline, color: KhatuColors.teal), title: Text(label), trailing: KpStatusBadge(status: status.toString(), dense: true));
}
