import QRCodeModel from '../models/QRCode.js';
import User from '../models/User.js';
import VirtualAccount from '../models/VirtualAccount.js';
import QRCode from 'qrcode';
import razorpayVA from './razorpayVirtualAccount.js';

function cleanHandlePart(value, fallback = 'user') {
  const cleaned = String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9.\-_]/g, '')
    .replace(/^[.\-_]+|[.\-_]+$/g, '');
  return cleaned.length >= 2 ? cleaned.slice(0, 24) : fallback;
}

async function buildUniqueKhatuUpiId(user) {
  if (user.khatuUpiId) return user.khatuUpiId;

  const namePart = cleanHandlePart(user.name, 'user');
  const mobilePart = String(user.mobile || user._id).replace(/\D/g, '').slice(-4);
  const base = cleanHandlePart(`${namePart}${mobilePart}`, `user${String(user._id).slice(-6)}`);

  let candidate = `${base}@khatupay`;
  let suffix = 1;
  while (await User.exists({ khatuUpiId: candidate, _id: { $ne: user._id } })) {
    candidate = `${base}${suffix}@khatupay`;
    suffix += 1;
  }

  user.khatuUpiId = candidate;
  await user.save();
  return candidate;
}

function getVirtualVpa(virtualAccount) {
  return virtualAccount?.receivers?.vpa?.find((item) => item?.address)?.address;
}

function buildUpiUri({ vpa, name, note, transactionRef }) {
  const params = new URLSearchParams({
    pa: vpa,
    pn: name || 'KhatuPay User',
    cu: 'INR'
  });
  if (note) params.set('tn', note);
  if (transactionRef) params.set('tr', transactionRef);
  return `upi://pay?${params.toString()}`;
}

export async function ensureUserPaymentQr(userId) {
  const user = await User.findById(userId);
  if (!user) throw new Error('User not found');

  const khatuUpiId = await buildUniqueKhatuUpiId(user);

  let virtualAccount = await VirtualAccount.findOne({ userId: user._id, isActive: true }).sort({ createdAt: -1 });
  if (!virtualAccount) {
    virtualAccount = await razorpayVA.createVirtualAccount(user._id, {
      description: `KhatuPay collection account for ${user.name || user.mobile}`
    });
  }

  const receiverVpa = getVirtualVpa(virtualAccount);
  const paymentVpa = receiverVpa || user.upiId || khatuUpiId;
  const qrId = `KPQR-${String(user._id).slice(-8)}-${Date.now()}`;
  const note = 'KhatuPay payment';
  const displayNumber = String(user.mobile || '').replace(/\D/g, '').slice(-10);
  const payerName = displayNumber || user.name || 'KhatuPay User';
  const uri = buildUpiUri({
    vpa: paymentVpa,
    name: payerName,
    note,
    transactionRef: qrId
  });
  const imagePath = await QRCode.toDataURL(uri, { type: 'image/png', width: 400, margin: 2 });

  const payload = {
    autoGenerated: true,
    qrId,
    pa: paymentVpa,
    pn: payerName,
    displayName: payerName,
    displayNumber,
    note,
    tn: note,
    uri,
    qrString: uri,
    khatuUpiId,
    receiverVpa,
    registeredMobile: displayNumber || user.mobile,
    routingMode: receiverVpa ? 'VIRTUAL_ACCOUNT' : (user.upiId ? 'USER_UPI' : 'KHATUPAY_ALIAS')
  };

  const existing = await QRCodeModel.findOne({
    userId: user._id,
    type: 'STATIC',
    isActive: true,
    'payload.autoGenerated': true
  }).sort({ createdAt: -1 });

  if (existing) {
    existing.virtualAccountId = virtualAccount?._id;
    existing.payload = { ...(existing.payload || {}), ...payload };
    existing.imagePath = imagePath;
    await existing.save();
    return existing;
  }

  return QRCodeModel.create({
    userId: user._id,
    type: 'STATIC',
    virtualAccountId: virtualAccount?._id,
    payload,
    imagePath,
    isActive: true
  });
}

export default ensureUserPaymentQr;
